### PR TITLE
feat: support vite 

### LINKED ISSUE #80: [Feature Request]: Support Vite
# Background

It's a amazing project, I using it in my project. But when i migrate to vite. I found style9 currently don't support it. So i want a vite plugin :)

## Others

I'll do it.

### PR DESCRIPTION
**Pull request by nonzzz**
This pull request will add a vite plugin

Fixes #80

### CODE REVIEW

**Review by johanholmerin — COMMENTED** [review]
Hi, thanks for this, it looks great. There are some failures in CI, can you take a look at them?

I've also have a question - since style9 has its own algorithm for resolving what styles get applied it requires that the generated CSS is in a deterministic order. It does this by **combining all the generated CSS into a single file** and [sorting the declarations](https://github.com/johanholmerin/style9/blob/master/docs/How-it-works.md#css-post-processing). This is done automatically by the other plugins but needs [manually if using the babel plugin](https://github.com/johanholmerin/style9/blob/master/docs/Bundler-plugins.md#babel). I'm not sure how this plugin can solve this if each file is loaded individually.

**Comment by nonzzz** [comment]
When i generator bundles from `vite` and run with my local services. I can get the right order in production.

**Comment by johanholmerin** [comment]
@nonzzz See video for a demo of the issue. This is not related to any bug in vite, it's a requirement of style9

https://user-images.githubusercontent.com/7433263/207795236-c732cbfd-e217-4c0b-a556-fce871e71d82.mov

**Comment by nonzzz** [comment]
@johanholmerin . All right. i got. i will fix them as soon

**Comment by nonzzz** [comment]
@johanholmerin  After thinking about. I'm make sure that should be handle in vite plugin. So in development mode. I will 
collect the css result and trigger vite hmr. ( To ensure that the css order  be right.

In production. I'm not sure how to put the css chunk to vite for it's own processing. ( So i implement 
the generator function.

**Comment by nonzzz** [comment]
Finally. I verified production.But i found the generator result use the virtual module id. In vite，the virtual module will be transformed as __x00__{virtual module name}. maybe it would to use hash name?

**Comment by johanholmerin** [comment]
I'm not sure what if Vite has some other behavior, but rollup has an [output.assetFileNames](https://rollupjs.org/guide/en/#outputassetfilenames) setting which can be used to change the name of the generated files, so I don't think you need to worry about the default name.

Everything seems to work as expected for me. @qodesmith @smokku You've been interested in a Vite plugin, can you help test this?

**Comment by nonzzz** [comment]
@johanholmerin Vite have a logic for inject final source to `index.html`  .( vite don't expose it's internal inject function. So when i rewrite the result it can be work well with vite.
I will pay more time to read vite source code. ( From the vite currently document. configServer is a black box. 
I think if this feature is passed. I can make it better.

**Pull request merged**
